### PR TITLE
prevented npm error relevant with missing nucleo-icons.svg file

### PR DESCRIPTION
**Pull request by haydar**
npm is throwing error relevant with missing nucleo-icons.svg file during npm run. I fixed this issue.

### CODE REVIEW

**Comment by resurtm** [comment]
@haydar, good catch. Also had this issue.

@alexandru-paduraru, can we merge this one? Would be some kind of cool. Thanks!

**Comment by haydar** [comment]
> @haydar, good catch. Also had this issue.
> 
> @alexandru-paduraru, can we merge this one? Would be some kind of cool. Thanks!

Merge please

**Comment by alexandru-paduraru** [comment]
@haydar thank you for the PR and contribution, just added my colleague @dragosct10 and he will schedule this merge.

**Comment by resurtm** [comment]
@haydar, @dragosct10, awesome thanks!

Can we also update npm package too? Looks like it has the old version:

https://www.npmjs.com/package/paper-dashboard-2

**Pull request merged**
